In [206]:
import numpy as np

## numpy arrays

In [207]:
myList = [20, 30, 40]

In [208]:
npArray = np.array(myList)

In [209]:
matrixList = [[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [210]:
matrixArray = np.array(matrixList)

## numpy methods

* #### arange

In [211]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [212]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* #### zeros and ones

In [214]:
np.zeros(5) # Returns an array of zeros

array([0., 0., 0., 0., 0.])

In [215]:
np.ones(5) # Returns an array of ones

array([1., 1., 1., 1., 1.])

In [216]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

* #### linspace

In [217]:
np.linspace(0,20,5) # (m, n, k) => Returns an aray of k elements which are seperated equally between m and n

array([ 0.,  5., 10., 15., 20.])

In [218]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

* #### eye

In [219]:
np.eye(3) # Returns a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [220]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

* #### random

In [221]:
np.random.randn(8) # Returns a n sized random list or n x m x ... x k random matrix

array([-0.53249209, -0.5902856 ,  0.84334248,  0.63354924,  0.91740335,
        0.10238941, -1.92288344,  0.50646163])

In [222]:
np.random.randn(3,3)

array([[-0.85970625,  0.77902486,  0.48525359],
       [ 2.14811973, -2.46189578,  0.44385761],
       [ 0.70916015, -0.91781118, -0.39323401]])

In [223]:
np.random.randint(1,10) # Returns a random int between min-max args

4

In [224]:
np.random.randint(1,700,8) # Returns a random int array

array([381, 158, 693,  50,  81, 563, 614, 244])

* ## array methods

In [225]:
npArr = np.random.randn(25)

In [226]:
npArr.reshape(5,5) # Returns the reshaped array (array can be reshaped as a matrix) !! should be used with valid args

array([[ 0.59101416, -0.50541683,  0.15343681, -1.24460189,  0.33461019],
       [-1.49748105,  1.71968277,  0.42734726, -2.00329435, -0.16365752],
       [-0.76243525,  0.42048828,  0.90905135, -0.71926145,  0.59628258],
       [ 1.44832951,  0.11047886, -0.27709373, -0.03068219, -0.91811416],
       [ 0.45157944, -0.3904766 , -0.02322583,  2.0684326 , -0.17094615]])

In [227]:
npArr.max()

2.068432598089616

In [228]:
npArr.min()

-2.0032943484508636

In [229]:
npArr.argmax() # Returns the index of the max element

23

In [230]:
npArr.argmin() # Returns the index of the min element

8

*  #### index operations with numpy arrays

> Everything works with standart lists also works with numpy arrays

In [231]:
npArr[5]

-1.497481050220605

In [232]:
npArr[3:8]

array([-1.24460189,  0.33461019, -1.49748105,  1.71968277,  0.42734726])

> But more things can be done with numpy array

In [233]:
npArr[2:5] = -5 # Assigns the value to the elements in the sliced part

In [234]:
npArr

array([ 0.59101416, -0.50541683, -5.        , -5.        , -5.        ,
       -1.49748105,  1.71968277,  0.42734726, -2.00329435, -0.16365752,
       -0.76243525,  0.42048828,  0.90905135, -0.71926145,  0.59628258,
        1.44832951,  0.11047886, -0.27709373, -0.03068219, -0.91811416,
        0.45157944, -0.3904766 , -0.02322583,  2.0684326 , -0.17094615])

In [235]:
anotherArr = np.arange(0,25)

In [236]:
slicedArr = anotherArr[3:10]

In [237]:
slicedArr[:] = 700 # Assigns the value to every element in the array

In [238]:
slicedArr

array([700, 700, 700, 700, 700, 700, 700])

In [239]:
anotherArr # More interesting part is main array is also changed when we change the sliced array

array([  0,   1,   2, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [240]:
copyArr = anotherArr.copy()[3:10] # To prevent the change in main array we should use a copy of it

In [241]:
copyArr[:] = 5

In [242]:
anotherArr # Still holds the old value

array([  0,   1,   2, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

*  #### index operations with matrices

In [243]:
matrixArray # Created at the first part

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

> Everything works with standart lists also works with numpy arrays

In [244]:
matrixArray[0]

array([10, 20, 30])

In [245]:
matrixArray[1][2]

40

> But more things can be done with numpy array

In [246]:
matrixArray[1,2] # Same with matrixArray[1][2]

40

In [247]:
matrixArray[0:, 2]

array([30, 40, 60])

In [248]:
matrixArray[0:, 2:]

array([[30],
       [40],
       [60]])

In [249]:
matrixArray[[2,0]]

array([[40, 50, 60],
       [10, 20, 30]])

## operations with numpy arrays

In [250]:
arrForOps = np.random.randint(-100,100,20)

In [251]:
arrForOps

array([-11, -12, -67,  48,  59, -88, -47, -20, -50, -15, -22,  -6, -36,
        63,  79,  62, -11, -81,  82,  -8])

In [252]:
arrForOps > 0

array([False, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
        True, False])

In [253]:
arrForOps[arrForOps > 0]

array([48, 59, 63, 79, 62, 82])

In [254]:
arrForOps + arrForOps

array([ -22,  -24, -134,   96,  118, -176,  -94,  -40, -100,  -30,  -44,
        -12,  -72,  126,  158,  124,  -22, -162,  164,  -16])

In [255]:
arrForOps * arrForOps

array([ 121,  144, 4489, 2304, 3481, 7744, 2209,  400, 2500,  225,  484,
         36, 1296, 3969, 6241, 3844,  121, 6561, 6724,   64])

In [256]:
arrForOps - arrForOps

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [257]:
np.sqrt(arrForOps[arrForOps > 0])

array([6.92820323, 7.68114575, 7.93725393, 8.88819442, 7.87400787,
       9.05538514])

In [258]:
np.square(arrForOps)

array([ 121,  144, 4489, 2304, 3481, 7744, 2209,  400, 2500,  225,  484,
         36, 1296, 3969, 6241, 3844,  121, 6561, 6724,   64])

In [259]:
np.min(arrForOps)

-88

In [260]:
np.max(arrForOps)

82

In [261]:
np.abs(arrForOps)

array([11, 12, 67, 48, 59, 88, 47, 20, 50, 15, 22,  6, 36, 63, 79, 62, 11,
       81, 82,  8])

In [262]:
np.sin(arrForOps)

array([ 0.99999021,  0.53657292,  0.85551998, -0.76825466,  0.63673801,
       -0.0353983 , -0.12357312, -0.91294525,  0.26237485, -0.65028784,
        0.00885131,  0.2794155 ,  0.99177885,  0.1673557 , -0.44411267,
       -0.7391807 ,  0.99999021,  0.62988799,  0.31322878, -0.98935825])

In [263]:
np.cos(arrForOps)

array([ 0.0044257 ,  0.84385396, -0.5177698 , -0.64014434, -0.77108022,
        0.99937328, -0.99233547,  0.40808206,  0.96496603, -0.75968791,
       -0.99996083,  0.96017029, -0.12796369,  0.98589658, -0.89597095,
        0.67350716,  0.0044257 ,  0.77668598,  0.9496777 , -0.14550003])

In [264]:
np.square(np.sin(arrForOps)) + np.square(np.cos(arrForOps))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])